name: Check milestone

on:
  workflow_dispatch:
  schedule:
    - cron: '10/15 * * * *'
jobs:
  build:
    name: Check milestone
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Conditions
      id: check_conditions
      run: |
        gh workflow disable 'Check milestone'
        echo 'foo'

    # - name: Send tg message
    #   env:
    #     TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    #   run: |
    #     set -e
    #     # echo curl -X POST \
    #     #   -H 'Content-Type: application/json' \
    #     #   -d '{"chat_id": "@marinade_stats_channel", "text": "'"$(./marinade-tvl-message.bash || exit 1)"'"}' \
    #     #   https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage
