name: Check milestone

on:
  workflow_dispatch:
  schedule:
    - cron: '10/15 * * * *'
jobs:
  build:
    name: Check milestone
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Milestone
      env:
        GH_TOKEN: ${{ github.token }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      run: |
        set -e

        if (( $(./marinade-tvl.bash || exit 1) >= 12000000 ))
        then
          gh workflow disable 'Check milestone'
          echo 'Milestone reached!'
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{"chat_id": "@marinade_stats_channel", "text": "🔥🔥🔥 12 M SOL reached 🔥🔥🔥"}' \
            https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage
        else
          echo 'Milestone not reached yet.'
        fi
